def addnumbers(x,y):
    return x+y
def subnumbers(x,y):
    return x-y
def multnumbers(x,y):
    return x*y
def divnumbers(x,y):
    return x/y
def findexpo(x,y):
    return x**y
def findroot(x):
    return x**0.5